CREATE TABLE C##ALESNAX.USERS 
(
  U_ID NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL
, U_EMAIL VARCHAR2(64 CHAR) NOT NULL 
, U_NAME VARCHAR2(64 CHAR) NOT NULL 
, U_SURNAME VARCHAR2(64 CHAR) NOT NULL 
, U_PASSWORD VARCHAR2(100 CHAR) NOT NULL 
, U_BIRTHDAY DATE 
, U_REGISTRATION_DATE DATE 
, CONSTRAINT USERS_PK PRIMARY KEY 
  (
    U_ID 
  )
  ENABLE 
);

ALTER TABLE C##ALESNAX.USERS
ADD CONSTRAINT USERS_UK1 UNIQUE 
(
  U_EMAIL 
)
ENABLE;


CREATE TABLE C##ALESNAX.LOCATIONS 
(
  LO_ID NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL
, LO_COUNTRY VARCHAR2(64 CHAR) NOT NULL 
, LO_CITY VARCHAR2(64 CHAR) NOT NULL 
, LO_STREET VARCHAR2(64 CHAR) NOT NULL 
, LO_BUILDING_NO VARCHAR2(20 CHAR) 
, CONSTRAINT LOCATIONS_PK PRIMARY KEY 
  (
    LO_ID 
  )
  ENABLE 
);


CREATE TABLE C##ALESNAX.TYPE_APARTMENTS 
(
  TY_ID NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL 
, TY_TYPE VARCHAR2(20 CHAR) NOT NULL 
, TY_DESCRIPTION VARCHAR2(256 CHAR) 
, CONSTRAINT TYPE_APARTMENTS_PK PRIMARY KEY 
  (
    TY_ID 
  )
  ENABLE 
);





CREATE TABLE C##ALESNAX.APARTMENTS 
(
  AP_ID NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL 
, AP_NAME VARCHAR2(128 CHAR) NOT NULL 
, AP_PRICE DECIMAL 
, AP_MAX_GUEST_NUMBER NUMBER 
, AP_TYPE_ID NUMBER 
, AP_LOCATION_ID NUMBER 
, CONSTRAINT APARTMENTS_PK PRIMARY KEY 
  (
    AP_ID 
  )
  ENABLE 
);

ALTER TABLE C##ALESNAX.APARTMENTS
ADD CONSTRAINT APARTMENTS_TYPE_APARTMENT_FK1 FOREIGN KEY
(
  AP_TYPE_ID 
)
REFERENCES C##ALESNAX.TYPE_APARTMENTS
(
  TY_ID 
)
ENABLE;


ALTER TABLE C##ALESNAX.APARTMENTS
ADD CONSTRAINT APARTMENTS_LOCATIONS_FK1 FOREIGN KEY
(
  AP_LOCATION_ID 
)
REFERENCES C##ALESNAX.LOCATIONS
(
  LO_ID 
)
ENABLE;



CREATE TABLE "C##ALESNAX"."BOOKINGS" 
   (	"BO_ID" NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL, 
	"BO_USER" NUMBER NOT NULL, 
	"BO_APARTMENT" NUMBER NOT NULL, 
	"BO_START" DATE NOT NULL, 
	"BO_END" DATE NOT NULL, 
	 CONSTRAINT "BOOKINGS_PK" PRIMARY KEY ("BO_ID"),
	 CONSTRAINT "BOOKINGS_USERS_FK1" FOREIGN KEY ("BO_USER")
	  REFERENCES "C##ALESNAX"."USERS" ("U_ID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "BOOKINGS_APARTMENTS_FK1" FOREIGN KEY ("BO_APARTMENT")
	  REFERENCES "C##ALESNAX"."APARTMENTS" ("AP_ID") ON DELETE CASCADE ENABLE
   ) ;




