
INSERT INTO "C##ALESNAX"."TYPE_APARTMENTS" (TY_TYPE, TY_DESCRIPTION) VALUES ('Entire home', 'Have a place to yourself');
INSERT INTO "C##ALESNAX"."TYPE_APARTMENTS" (TY_TYPE, TY_DESCRIPTION) VALUES ('Private room', 'Have your own room and share some common spaces');
INSERT INTO "C##ALESNAX"."TYPE_APARTMENTS" (TY_TYPE, TY_DESCRIPTION) VALUES ('Shared room', 'Stay in a shared space, like a common room');

INSERT INTO "C##ALESNAX"."LOCATIONS" (LO_COUNTRY, LO_CITY, LO_STREET, LO_BUILDING_NO) VALUES ('Belarus', 'Hrodna', 'Pashkevich', '3a');
INSERT INTO "C##ALESNAX"."LOCATIONS" (LO_COUNTRY, LO_CITY, LO_STREET, LO_BUILDING_NO) VALUES ('Belarus', 'Hrodna', 'Mitskeviecha', '1');
INSERT INTO "C##ALESNAX"."LOCATIONS" (LO_COUNTRY, LO_CITY, LO_STREET, LO_BUILDING_NO) VALUES ('Belarus', 'Brest', 'Kalinouskaha', '34');
INSERT INTO "C##ALESNAX"."LOCATIONS" (LO_COUNTRY, LO_CITY, LO_STREET, LO_BUILDING_NO) VALUES ('Belarus', 'Brest', 'Kalinouskaha', '45');
INSERT INTO "C##ALESNAX"."LOCATIONS" (LO_COUNTRY, LO_CITY, LO_STREET, LO_BUILDING_NO) VALUES ('Belarus', 'Minsk', 'Muliavina', '23');
INSERT INTO "C##ALESNAX"."LOCATIONS" (LO_COUNTRY, LO_CITY, LO_STREET, LO_BUILDING_NO) VALUES ('Belarus', 'Minsk', 'Brouki', '2');
INSERT INTO "C##ALESNAX"."LOCATIONS" (LO_COUNTRY, LO_CITY, LO_STREET, LO_BUILDING_NO) VALUES ('Lithuania', 'Vilnius', 'Vitautas', '1');
INSERT INTO "C##ALESNAX"."LOCATIONS" (LO_COUNTRY, LO_CITY, LO_STREET, LO_BUILDING_NO) VALUES ('Lithuania', 'Vilnius', 'Yahayla', '52');
INSERT INTO "C##ALESNAX"."LOCATIONS" (LO_COUNTRY, LO_CITY, LO_STREET, LO_BUILDING_NO) VALUES ('Lithuania', 'Vilnius', 'Vitautas', '16');
INSERT INTO "C##ALESNAX"."LOCATIONS" (LO_COUNTRY, LO_CITY, LO_STREET, LO_BUILDING_NO) VALUES ('Lithuania', 'Vilnius', 'Mindaugasa', '32');
INSERT INTO "C##ALESNAX"."LOCATIONS" (LO_COUNTRY, LO_CITY, LO_STREET, LO_BUILDING_NO) VALUES ('Lithuania', 'Vilnius', 'Vitautas', '76');
INSERT INTO "C##ALESNAX"."LOCATIONS" (LO_COUNTRY, LO_CITY, LO_STREET, LO_BUILDING_NO) VALUES ('Lithuania', 'Klaipeda', 'Yahayla', '123');
INSERT INTO "C##ALESNAX"."LOCATIONS" (LO_COUNTRY, LO_CITY, LO_STREET, LO_BUILDING_NO) VALUES ('Lithuania', 'Klaipeda', 'Mitskevica', '43');
INSERT INTO "C##ALESNAX"."LOCATIONS" (LO_COUNTRY, LO_CITY, LO_STREET, LO_BUILDING_NO) VALUES ('Lithuania', 'Klaipeda', 'Mindaugasa', '87');
INSERT INTO "C##ALESNAX"."LOCATIONS" (LO_COUNTRY, LO_CITY, LO_STREET, LO_BUILDING_NO) VALUES ('Ukraine', 'Lviv', 'Zalataya Hara', '12');
INSERT INTO "C##ALESNAX"."LOCATIONS" (LO_COUNTRY, LO_CITY, LO_STREET, LO_BUILDING_NO) VALUES ('Ukraine', 'Lviv', 'Chernovola', '111');
INSERT INTO "C##ALESNAX"."LOCATIONS" (LO_COUNTRY, LO_CITY, LO_STREET, LO_BUILDING_NO) VALUES ('Ukraine', 'Lviv', 'Akademichna', '58');
INSERT INTO "C##ALESNAX"."LOCATIONS" (LO_COUNTRY, LO_CITY, LO_STREET, LO_BUILDING_NO) VALUES ('Ukraine', 'Lviv', 'Chernovola', '36');
INSERT INTO "C##ALESNAX"."LOCATIONS" (LO_COUNTRY, LO_CITY, LO_STREET, LO_BUILDING_NO) VALUES ('Ukraine', 'Lviv', 'Rynak', '2');
INSERT INTO "C##ALESNAX"."LOCATIONS" (LO_COUNTRY, LO_CITY, LO_STREET, LO_BUILDING_NO) VALUES ('Ukraine', 'Kiev', 'Pochtova', '24');
INSERT INTO "C##ALESNAX"."LOCATIONS" (LO_COUNTRY, LO_CITY, LO_STREET, LO_BUILDING_NO) VALUES ('Ukraine', 'Kiev', 'Khreschatik', '41');





INSERT INTO "C##ALESNAX"."APARTMENTS" (AP_NAME, AP_PRICE, AP_MAX_GUEST_NUMBER, AP_TYPE_ID, AP_LOCATION_ID) VALUES ('Stary Horad ', '35', '1', '1', '1');
INSERT INTO "C##ALESNAX"."APARTMENTS" (AP_NAME, AP_PRICE, AP_MAX_GUEST_NUMBER, AP_TYPE_ID, AP_LOCATION_ID) VALUES ('Old city app', '45', '2', '1', '2');
INSERT INTO "C##ALESNAX"."APARTMENTS" (AP_NAME, AP_PRICE, AP_MAX_GUEST_NUMBER, AP_TYPE_ID, AP_LOCATION_ID) VALUES ('Center Tower room', '23', '3', '2', '3');
INSERT INTO "C##ALESNAX"."APARTMENTS" (AP_NAME, AP_PRICE, AP_MAX_GUEST_NUMBER, AP_TYPE_ID, AP_LOCATION_ID) VALUES ('Big city room', '56', '4', '3', '4');
INSERT INTO "C##ALESNAX"."APARTMENTS" (AP_NAME, AP_PRICE, AP_MAX_GUEST_NUMBER, AP_TYPE_ID, AP_LOCATION_ID) VALUES ('Great people apartments', '34', '5', '1', '5');
INSERT INTO "C##ALESNAX"."APARTMENTS" (AP_NAME, AP_PRICE, AP_MAX_GUEST_NUMBER, AP_TYPE_ID, AP_LOCATION_ID) VALUES ('Brouki fashion room', '89', '4', '2', '6');
INSERT INTO "C##ALESNAX"."APARTMENTS" (AP_NAME, AP_PRICE, AP_MAX_GUEST_NUMBER, AP_TYPE_ID, AP_LOCATION_ID) VALUES ('Legend house', '12', '7', '1', '7');
INSERT INTO "C##ALESNAX"."APARTMENTS" (AP_NAME, AP_PRICE, AP_MAX_GUEST_NUMBER, AP_TYPE_ID, AP_LOCATION_ID) VALUES ('central house', '34', '3', '1', '8');
INSERT INTO "C##ALESNAX"."APARTMENTS" (AP_NAME, AP_PRICE, AP_MAX_GUEST_NUMBER, AP_TYPE_ID, AP_LOCATION_ID) VALUES ('Deep water room', '45', '4', '2', '9');
INSERT INTO "C##ALESNAX"."APARTMENTS" (AP_NAME, AP_PRICE, AP_MAX_GUEST_NUMBER, AP_TYPE_ID, AP_LOCATION_ID) VALUES ('Litva stylish house', '11', '6', '1', '10');
INSERT INTO "C##ALESNAX"."APARTMENTS" (AP_NAME, AP_PRICE, AP_MAX_GUEST_NUMBER, AP_TYPE_ID, AP_LOCATION_ID) VALUES ('TTut i tam apartments', '56', '3', '2', '11');
INSERT INTO "C##ALESNAX"."APARTMENTS" (AP_NAME, AP_PRICE, AP_MAX_GUEST_NUMBER, AP_TYPE_ID, AP_LOCATION_ID) VALUES ('Here nowhere', '30', '2', '1', '12');
INSERT INTO "C##ALESNAX"."APARTMENTS" (AP_NAME, AP_PRICE, AP_MAX_GUEST_NUMBER, AP_TYPE_ID, AP_LOCATION_ID) VALUES ('New apartments for you', '40', '2', '1', '13');
INSERT INTO "C##ALESNAX"."APARTMENTS" (AP_NAME, AP_PRICE, AP_MAX_GUEST_NUMBER, AP_TYPE_ID, AP_LOCATION_ID) VALUES ('Here you can sleep home', '25', '3', '3', '14');
INSERT INTO "C##ALESNAX"."APARTMENTS" (AP_NAME, AP_PRICE, AP_MAX_GUEST_NUMBER, AP_TYPE_ID, AP_LOCATION_ID) VALUES ('House full of pleasure', '20', '7', '3', '15');
INSERT INTO "C##ALESNAX"."APARTMENTS" (AP_NAME, AP_PRICE, AP_MAX_GUEST_NUMBER, AP_TYPE_ID, AP_LOCATION_ID) VALUES ('Room as room', '30', '4', '2', '16');
INSERT INTO "C##ALESNAX"."APARTMENTS" (AP_NAME, AP_PRICE, AP_MAX_GUEST_NUMBER, AP_TYPE_ID, AP_LOCATION_ID) VALUES ('Beautiful room in Lviv', '45', '6', '2', '17');
INSERT INTO "C##ALESNAX"."APARTMENTS" (AP_NAME, AP_PRICE, AP_MAX_GUEST_NUMBER, AP_TYPE_ID, AP_LOCATION_ID) VALUES ('Chornovola fresh house', '665', '4', '1', '18');
INSERT INTO "C##ALESNAX"."APARTMENTS" (AP_NAME, AP_PRICE, AP_MAX_GUEST_NUMBER, AP_TYPE_ID, AP_LOCATION_ID) VALUES ('Rynak old hostel', '25', '3', '3', '19');
INSERT INTO "C##ALESNAX"."APARTMENTS" (AP_NAME, AP_PRICE, AP_MAX_GUEST_NUMBER, AP_TYPE_ID, AP_LOCATION_ID) VALUES ('Lviv old house', '15', '2', '3', '20');
INSERT INTO "C##ALESNAX"."APARTMENTS" (AP_NAME, AP_PRICE, AP_MAX_GUEST_NUMBER, AP_TYPE_ID, AP_LOCATION_ID) VALUES ('Guest  house kiev', '50', '5', '1', '21');
INSERT INTO "C##ALESNAX"."APARTMENTS" (AP_NAME, AP_PRICE, AP_MAX_GUEST_NUMBER, AP_TYPE_ID, AP_LOCATION_ID) VALUES ('Maidan nere house', '20', '5', '1', '13');






INSERT INTO "C##ALESNAX"."USERS" ("U_EMAIL ", U_NAME, U_SURNAME, U_PASSWORD) VALUES ('alesnax@gmail.com', 'John', 'Smith', 'asdgjlasdgl;sdfy');
INSERT INTO "C##ALESNAX"."USERS" ("U_EMAIL ", U_NAME, U_SURNAME, U_PASSWORD) VALUES ('shady@yahoo.com', 'Jim', 'Morrison', 'asdgml;346');
INSERT INTO "C##ALESNAX"."USERS" ("U_EMAIL ", U_NAME, U_SURNAME, U_PASSWORD) VALUES ('ukul@gmail.com', 'Chloe', 'Merrow', '123512ok37');
INSERT INTO "C##ALESNAX"."USERS" ("U_EMAIL ", U_NAME, U_SURNAME, U_PASSWORD) VALUES ('asaser@gmail.com', 'Nancy', 'Bobthinsky', '123kop56jl;,');
INSERT INTO "C##ALESNAX"."USERS" ("U_EMAIL ", U_NAME, U_SURNAME, U_PASSWORD) VALUES ('qwerun@yahoo.com', 'Kary', 'Price', '23j;lajerl;');
INSERT INTO "C##ALESNAX"."USERS" ("U_EMAIL ", U_NAME, U_SURNAME, U_PASSWORD) VALUES ('zaszu@gmail.com', 'Donald', 'Trumpy', 'hsdfklgh344236l');
INSERT INTO "C##ALESNAX"."USERS" ("U_EMAIL ", U_NAME, U_SURNAME, U_PASSWORD) VALUES ('kasd@gmail.com', 'Alex', 'Dirk', '45h763357g3i4jgi');
INSERT INTO "C##ALESNAX"."USERS" ("U_EMAIL ", U_NAME, U_SURNAME, U_PASSWORD) VALUES ('smith@yahoo.com', 'Moritz', 'Gaga', '37ouo37hjio');
INSERT INTO "C##ALESNAX"."USERS" ("U_EMAIL ", U_NAME, U_SURNAME, U_PASSWORD) VALUES ('neom@gmail.com', 'Kola', 'Coca', '357oihj7iop57p');
INSERT INTO "C##ALESNAX"."USERS" ("U_EMAIL ", U_NAME, U_SURNAME, U_PASSWORD) VALUES ('naobi@yahoo.com', 'Jami', 'Smothy', 'erwhioh342io65');
INSERT INTO "C##ALESNAX"."USERS" ("U_EMAIL ", U_NAME, U_SURNAME, U_PASSWORD) VALUES ('asterix@gmail.com', 'Kerry', 'Parry', 'jwergj6ig234yu6');
INSERT INTO "C##ALESNAX"."USERS" ("U_EMAIL ", U_NAME, U_SURNAME, U_PASSWORD) VALUES ('totalstar@yahoo.com', 'Anna', 'Diego', '234hu623f46');
INSERT INTO "C##ALESNAX"."USERS" ("U_EMAIL ", U_NAME, U_SURNAME, U_PASSWORD) VALUES ('asdorka@gmail.com', 'AAzis', 'Daga', '23g46f3vf6i');
INSERT INTO "C##ALESNAX"."USERS" ("U_EMAIL ", U_NAME, U_SURNAME, U_PASSWORD) VALUES ('vaoin@gmail.com', 'Nancy', 'Rambo', '234v6jkl2346ivl;2');
INSERT INTO "C##ALESNAX"."USERS" ("U_EMAIL ", U_NAME, U_SURNAME, U_PASSWORD) VALUES ('kashamalasha@gmail.com', 'Yota', 'Space', '2346igvui346');
INSERT INTO "C##ALESNAX"."USERS" ("U_EMAIL ", U_NAME, U_SURNAME, U_PASSWORD) VALUES ('jakome@yahoo.com', 'Johanna', 'Fallow', '7bg45jig7ojk');
INSERT INTO "C##ALESNAX"."USERS" ("U_EMAIL ", U_NAME, U_SURNAME, U_PASSWORD) VALUES ('ased@gmail.com', 'Oleg', 'Novik', '357jk357oh57ko');
INSERT INTO "C##ALESNAX"."USERS" ("U_EMAIL ", U_NAME, U_SURNAME, U_PASSWORD) VALUES ('hanop@gmail.com', 'Nikolas', 'Maduro', '3bvg7iljk');
INSERT INTO "C##ALESNAX"."USERS" ("U_EMAIL ", U_NAME, U_SURNAME, U_PASSWORD) VALUES ('gimi@yahoo.com', 'Katy', 'Holms', '3jil33kgf7jkcj23kc56');
INSERT INTO "C##ALESNAX"."USERS" ("U_EMAIL ", U_NAME, U_SURNAME, U_PASSWORD) VALUES ('tetra@gmail.com', 'Veronica', 'Dsemesh', '234j6b23o;4jb6;2346;');
INSERT INTO "C##ALESNAX"."USERS" ("U_EMAIL ", U_NAME, U_SURNAME, U_PASSWORD) VALUES ('asdfasdg@gmail.com', 'Joja', 'Jaja', 'asdhgrhuq3gf2hu51f23u5');

INSERT INTO "C##ALESNAX"."BOOKINGS" (BO_USER, BO_APARTMENT, BO_START, BO_END) VALUES ('5', '4', TO_DATE('17-APR-04', 'DD-MON-RR'), TO_DATE('17-APR-10', 'DD-MON-RR'));
INSERT INTO "C##ALESNAX"."BOOKINGS" (BO_USER, BO_APARTMENT, BO_START, BO_END) VALUES ('6', '8', TO_DATE('17-APR-07', 'DD-MON-RR'), TO_DATE('17-APR-11', 'DD-MON-RR'));






















