CREATE TABLE if not EXISTS USERS (
  	U_ID INT(10) NOT NULL AUTO_INCREMENT,
	U_EMAIL VARCHAR(64) NOT NULL,
	U_NAME VARCHAR(64) NOT NULL,
	U_SURNAME VARCHAR(64) NOT NULL,
	U_PASSWORD VARCHAR(100) NOT NULL,
	U_BIRTHDAY DATE,
	 PRIMARY KEY (U_ID)
); 

ALTER TABLE USERS ADD CONSTRAINT U_ID_UNIQUE UNIQUE(U_ID);
ALTER TABLE USERS ADD CONSTRAINT U_EMAIL_UNIQUE UNIQUE(U_EMAIL);